try {
    a = 10 / 2;
    printd(a);
} catch (DivisionByZero) {
    printe("Caught division by zero exception");
}